### ISSUE TITLE
semantic-release version crashes with InvalidVersion exception via GitHub Action

### ISSUE THREAD

**Issue by mraniki** [python-semantic-release/python-semantic-release#645] opened 2023-07-19 08:24 UTC
## The problem

semantic-release version crashes with InvalidVersion exception

## Expected behavior

Expecting a version upgrade from 4.0.0 to 4.0.1 

## Environment

Done via the GitHub Action on ubuntu-latest

    release:
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      runs-on: ubuntu-latest
      permissions:
          id-token: write
          contents: write
      steps:
        - uses: actions/checkout@v3.5.3
          with:
            fetch-depth: 0
  
        - name: Semantic Version and Release
          id: release
          uses: relekang/python-semantic-release@v8.0.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            root_options: -vv

Build command `pip install poetry && poetry build`

## Configuration

[tool.semantic_release]
upload_to_vcs_release = false
version_variables = ["pyproject.toml:version","tt/utils.py:__version__"]
build_command = "pip install poetry && poetry build"
commit_parser = "emoji"

[tool.semantic_release.commit_parser_options]
major_tags = [
    "BREAKING",
    "💥",
    ":boom:",
  ]
minor_tags = ["feat",
    "🥚",":egg:",
    "🚀",":rocket:",
    "💄",":lipstick:",
    "✨",":sparkles:",
]

patch_tags = ["fix","bump","Update",
    "🎨",":art:",
    "🐛",":bug:",
    "🚑",":ambulance:",
    "⚡",":zap:",
    "🔥",":fire:",
    "🚨",":rotating_light:",
    "♻️",":recycle:",
    "🔧",":wrench:",
    "⬆️",":arrow_up:",
    "🩹",":adhesive_bandage:",
    "👷",":construction_worker:",
    "📝",":memo:",
    "🔒",":lock:",
    "👽",":alien:",
    "💬",":speech_balloon:",
    "🥅",":goal_net:",
    "✅",":white_check_mark:",
    "🐳",":whale:",
    "🙈",":see_no_evil:",
    "⚗️",":alembic:",
    "🧐",":monocle_face:",
    "🔇",":mute:",
    "🔊",":volume:",
]

## Logs

[07:37:04] DEBUG    [semantic_release.cli.commands.main] DEBUG       main.py:105
                    main.main: logging level set to: DEBUG                      
           DEBUG    [git.util] DEBUG util.is_cygwin_git: Failed      util.py:405
                    checking if running in CYGWIN due to:                       
                    FileNotFoundError(2, 'No such file or                       
                    directory')                                                 
           DEBUG    [semantic_release.cli.commands.main] DEBUG       main.py:123
                    main.main: global cli options:                              
                    GlobalCommandLineOptions(noop=False,                        
                    verbosity=2, config_file='pyproject.toml',                  
                    strict=False)                                               
           INFO     [semantic_release.cli.util] INFO                  util.py:84
                    util.load_raw_config_file: Loading configuration            
                    from pyproject.toml                                         
           DEBUG    [semantic_release.cli.util] DEBUG                 util.py:87
                    util.load_raw_config_file: Trying to parse                  
                    configuration pyproject.toml in TOML format                 
           INFO     [semantic_release.cli.config] INFO             config.py:228
                    config.select_branch_options: Using group                   
                    'main' options, as '(main|master)' matches                  
                    'main'                                                      
           DEBUG    [semantic_release.hvcs.util] DEBUG                util.py:45
                    util.build_requests_session: setting up default             
                    session authentication                                      
           DEBUG    [semantic_release.changelog.template] DEBUG   template.py:51
                    template.environment: {'template_dir':                      
                    'templates', 'block_start_string': '{%',                    
                    'block_end_string': '%}',                                   
                    'variable_start_string': '{{',                              
                    'variable_end_string': '}}',                                
                    'comment_start_string': '{#',                               
                    'comment_end_string': '#}',                                 
                    'line_statement_prefix': None,                              
                    'line_comment_prefix': None, 'trim_blocks':                 
                    False, 'lstrip_blocks': False,                              
                    'newline_sequence': '\n',                                   
                    'keep_trailing_newline': False, 'extensions':               
                    (), 'autoescape': True, 'autoescape_value':                 
                    True}                                                       
           DEBUG    [semantic_release.version.translator] DEBUG translator.py:40
                    translator._invert_tag_format_to_re:                        
                    inverted tag_format 'v{version}' to                         
                    'v(?P<version>.*)'                                          
           DEBUG    [semantic_release.cli.masking_filter]   masking_filter.py:30
                    DEBUG masking_filter.add_mask_for:                          
                    Adding redact pattern                                       
                    'context.hvcs_client.token' to                              
                    _redact_patterns                                            
           DEBUG    [semantic_release.cli.masking_filter]   masking_filter.py:30
                    DEBUG masking_filter.add_mask_for:                          
                    Adding redact pattern                                       
                    'context.hvcs_client.token' to                              
                    _redact_patterns                                            
           DEBUG    [semantic_release.cli.commands.version] DEBUG  version.py:48
                    version.is_forced_prerelease: force_prerelease              
                    = False, force_level = None, prerelease =                   
                    False                                                       
           DEBUG    [semantic_release.version.version] DEBUG      version.py:126
                    version.parse: attempting to parse string                   
                    '0.3' as Version                                            
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/semantic-release/semantic_release/__main__.py", line 6, in <module>
    main(args=sys.argv[1:])
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/semantic-release/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/semantic-release/semantic_release/cli/commands/version.py", line 274, in version
    new_version = next_version(
  File "/semantic-release/semantic_release/version/algorithm.py", line 241, in next_version
    all_git_tags_as_versions = tags_and_versions(repo.tags, translator)
  File "/semantic-release/semantic_release/version/algorithm.py", line 42, in tags_and_versions
    version = translator.from_tag(tag.name)
  File "/semantic-release/semantic_release/version/translator.py", line 73, in from_tag
    return self.from_string(raw_version_str)
  File "/semantic-release/semantic_release/version/translator.py", line 56, in from_string
    return Version.parse(
  File "/semantic-release/semantic_release/version/version.py", line 129, in parse
    raise InvalidVersion(f"{version_str!r} is not a valid Version")
semantic_release.version.version.InvalidVersion: '0.3' is not a valid Version

## Additional context

I only got the issue with 2 repo out of 5 no other issue for my other packages/release. My GitHub Action are done via reusable workflow for all the 5 repos.

**Comment by mraniki** [comment] 2023-07-19 15:27
here the trace for an example where it is working :
https://github.com/mraniki/talkytrend/actions/runs/5601009706/jobs/10244282014
it seems to be due to history being pulled maybe.

**Comment by roggervalf** [comment] 2023-07-20 17:09
same as above, https://github.com/taskforcesh/bullmq/actions/runs/5613809780/job/15210638375 an example of this failure

**Comment by bernardcooke53** [comment] 2023-07-20 21:37
I have raised #649 for this. v7 also skipped unparseable tags, so I'm not expecting the change to result in breakages, but if anyone would like to have a look I'd be grateful

**Comment by roggervalf** [comment] 2023-07-20 22:00
hi @bernardcooke53, hope the pr could solve this issue, thank you

**Comment by bernardcooke53** [comment] 2023-07-21 16:34
@roggervalf PR merged & released in 8.0.3

**Comment by roggervalf** [comment] 2023-07-21 17:39
thank you @bernardcooke53, now it's working, I only have one concern, now looks like the placeholder `<!--next-version-placeholder-->` is ignored, the changelog is regenerated with all the previous commits, and not only taking the last ones, as an example https://github.com/taskforcesh/bullmq/commit/59d4d1dd67a0efbab6ff252b2a042fc61c3f4df2

**Comment by mraniki** [comment] 2023-07-21 17:55
I confirm it is working for one of my failed repo as well. Thank you for the quick fix @bernardcooke53  👍 I think this can be closed.

**Comment by roggervalf** [comment] 2023-07-21 19:10
yeah I can confirm InvalidVersion exception is fixed, my new issue is related to this way of handling changelog https://python-semantic-release.readthedocs.io/en/latest/changelog_templates.html#migrating-an-existing-changelog

**Comment by bernardcooke53** [comment] 2023-07-21 19:35
Thank you for confirming - @roggervalf I have raised #652 as a separate issue, will close this now

**Closed by bernardcooke53** 2023-07-21 19:35 UTC
Labels: bug
