### ISSUE TITLE
configure changelog.md.j2 to have only final releases in the generated changelog.md

### ISSUE THREAD

**Issue by intex46** [python-semantic-release/python-semantic-release#837] opened 2024-02-14 16:27 UTC
Python version: 3.10
python_semantic_release==8.5.2

Hello, can you provide me an example of changelog.md.j2 in order to include changes made in pre-releases and alpha-releases in the final release section 

Actual Changelog.md:
```
# CHANGELOG

v0.2.1 (2024-02-14)
Chore
chore(release): release v0.2.1 [skip ci]
v0.2.1-rc.1 (2024-02-14)
Build
build: blablablah
Ci
ci: blablablah
Fix
fix: fix bug1 and bug2
v0.2.0 (2024-02-13)
```
The desired Changelog.md:
```
# CHANGELOG

v0.2.1 (2024-02-14)
Chore
chore(release): release v0.2.1 [skip ci]
Build
build: blablablah
Ci
ci: blablablah
Fix
fix: fix bug1 and bug2
v0.2.0 (2024-02-13)
```

**Comment by codejedi365** [comment] 2024-02-15 04:50
I don't believe this is doable easily from a template. You would likely have to write a fairly complex jinja macro to accomplish this.

To believe this is a duplicate of a recent request, #817. I have not had the cycles to put towards this idea yet although I fully agree it should be the default.

**Comment by codejedi365** [comment] 2024-02-17 02:05
Yes, when I finish with the current multi branch bugs, I will implement something like this.

**Closed** 2024-02-21 19:34 UTC
Labels: question
